#!/usr/bin/env bash

source ./src/utils.sh
source ./src/packages.sh

print_message "Updating system and installing required packages"
install_packages

print_message "System updated and packages installed"
