#!/usr/bin/env bash

source ./src/utils.sh
source ./src/packages.sh

VERBOSE=false

while getopts ":v" option; do
  case $option in
    v)
      VERBOSE=true;;
  esac
done

update_and_install_packages

print_block_message "Installation completed"
