#!/usr/bin/env bash

# versions

ZLIB_VERSION="1.3.1"
HDF5_VERSION="1.14.4.3"
NETCDF_C_VERSION="4.9.2"
NETCDF_F_VERSION="4.6.1"
LIBPNG_VERSION="1.6.43"

# utils

RED=$'\e[0;31m'
GREEN=$'\e[0;32m'
NC=$'\e[0m'

# zlib

ZLIB_DIR=${HOME}/zlib
ZLIB_BUILD=${HOME}/zlib_build
ZLIB_INSTALL=/usr/local

# hdf5

HDF5_DIR=${HOME}/hdf5
HDF5_BUILD=${HOME}/hdf5_build
HDF5_INSTALL=/usr/local

# netcdf

NETCDF_C_DIR=${HOME}/netcdf-c
NETCDF_C_BUILD=${HOME}/netcdf-c_build
NETCDF_F_DIR=${HOME}/netcdf-f
NETCDF_F_BUILD=${HOME}/netcdf-f_build
NETCDF_INSTALL=${HOME}/WRF/libraries/netcdf

# libpng

LIBPNG_DIR=${HOME}/libpng
LIBPNG_BUILD=${HOME}/libpng_build
LIBPNG_INSTALL=${HOME}/WRF/libraries/grib2
